### ISSUE TITLE
Create user table and User object

### ISSUE THREAD

**Issue by DenSev** [itechart-vitebsk-lab/socnet-java-training#3]
user has at least following fields:
* id - autogenerated
* username - not null
* password - not null
* firstName - not null
* lastName - not null 
* dateOfBirth - nullable
* dateRegistered - set automatically
* role - user/admin, not null

created a test admin user

**Comment by bramberry** [comment]
https://github.com/itechart-vitebsk-lab/socnet-java-training/pull/10
