### ISSUE TITLE
Implement token-based authentication

### ISSUE THREAD

**Issue by DenSev** [itechart-vitebsk-lab/socnet-java-training#5]
user passes username and password and receives a generated token
token is stored in a separate db table
token has following fields:
* token - unique generated hash, primary key
* userId - id of associated user
* expirationDate - date and time when token will be deleted, set automatically to N hours after creation

**Comment by bramberry** [comment]
https://github.com/itechart-vitebsk-lab/socnet-java-training/pull/14
